---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - destinationrules
  - envoyfilters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resilience.shedpilot.io
  resources:
  - adaptivepolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resilience.shedpilot.io
  resources:
  - adaptivepolicies/finalizers
  verbs:
  - update
- apiGroups:
  - resilience.shedpilot.io
  resources:
  - adaptivepolicies/status
  verbs:
  - get
  - patch
  - update
