//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptiveConcurrencyConfig) DeepCopyInto(out *AdaptiveConcurrencyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptiveConcurrencyConfig.
func (in *AdaptiveConcurrencyConfig) DeepCopy() *AdaptiveConcurrencyConfig {
	if in == nil {
		return nil
	}
	out := new(AdaptiveConcurrencyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptiveConcurrencyOverride) DeepCopyInto(out *AdaptiveConcurrencyOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptiveConcurrencyOverride.
func (in *AdaptiveConcurrencyOverride) DeepCopy() *AdaptiveConcurrencyOverride {
	if in == nil {
		return nil
	}
	out := new(AdaptiveConcurrencyOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptivePolicy) DeepCopyInto(out *AdaptivePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptivePolicy.
func (in *AdaptivePolicy) DeepCopy() *AdaptivePolicy {
	if in == nil {
		return nil
	}
	out := new(AdaptivePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdaptivePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptivePolicyList) DeepCopyInto(out *AdaptivePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdaptivePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptivePolicyList.
func (in *AdaptivePolicyList) DeepCopy() *AdaptivePolicyList {
	if in == nil {
		return nil
	}
	out := new(AdaptivePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdaptivePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptivePolicySpec) DeepCopyInto(out *AdaptivePolicySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AdaptiveConcurrency != nil {
		in, out := &in.AdaptiveConcurrency, &out.AdaptiveConcurrency
		*out = new(AdaptiveConcurrencyConfig)
		**out = **in
	}
	if in.AdmissionControl != nil {
		in, out := &in.AdmissionControl, &out.AdmissionControl
		*out = new(AdmissionControlConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.StreamingProtection != nil {
		in, out := &in.StreamingProtection, &out.StreamingProtection
		*out = new(StreamingProtectionConfig)
		**out = **in
	}
	if in.Profiles != nil {
		in, out := &in.Profiles, &out.Profiles
		*out = make(map[string]ProfileConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Triggers != nil {
		in, out := &in.Triggers, &out.Triggers
		*out = make([]TriggerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Schedules != nil {
		in, out := &in.Schedules, &out.Schedules
		*out = make([]ScheduleConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SignalConfig != nil {
		in, out := &in.SignalConfig, &out.SignalConfig
		*out = new(SignalConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptivePolicySpec.
func (in *AdaptivePolicySpec) DeepCopy() *AdaptivePolicySpec {
	if in == nil {
		return nil
	}
	out := new(AdaptivePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptivePolicyStatus) DeepCopyInto(out *AdaptivePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProfileActiveSince != nil {
		in, out := &in.ProfileActiveSince, &out.ProfileActiveSince
		*out = (*in).DeepCopy()
	}
	if in.ActiveFilters != nil {
		in, out := &in.ActiveFilters, &out.ActiveFilters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ManagedResources != nil {
		in, out := &in.ManagedResources, &out.ManagedResources
		*out = make([]ManagedResource, len(*in))
		copy(*out, *in)
	}
	if in.LastDecision != nil {
		in, out := &in.LastDecision, &out.LastDecision
		*out = new(DecisionRecord)
		(*in).DeepCopyInto(*out)
	}
	if in.DecisionHistory != nil {
		in, out := &in.DecisionHistory, &out.DecisionHistory
		*out = make([]DecisionRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NextTriggerEvaluation != nil {
		in, out := &in.NextTriggerEvaluation, &out.NextTriggerEvaluation
		*out = (*in).DeepCopy()
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptivePolicyStatus.
func (in *AdaptivePolicyStatus) DeepCopy() *AdaptivePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AdaptivePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionControlConfig) DeepCopyInto(out *AdmissionControlConfig) {
	*out = *in
	if in.SuccessCodes != nil {
		in, out := &in.SuccessCodes, &out.SuccessCodes
		*out = make([]HTTPStatusRange, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionControlConfig.
func (in *AdmissionControlConfig) DeepCopy() *AdmissionControlConfig {
	if in == nil {
		return nil
	}
	out := new(AdmissionControlConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionControlOverride) DeepCopyInto(out *AdmissionControlOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionControlOverride.
func (in *AdmissionControlOverride) DeepCopy() *AdmissionControlOverride {
	if in == nil {
		return nil
	}
	out := new(AdmissionControlOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionRecord) DeepCopyInto(out *DecisionRecord) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionRecord.
func (in *DecisionRecord) DeepCopy() *DecisionRecord {
	if in == nil {
		return nil
	}
	out := new(DecisionRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPStatusRange) DeepCopyInto(out *HTTPStatusRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPStatusRange.
func (in *HTTPStatusRange) DeepCopy() *HTTPStatusRange {
	if in == nil {
		return nil
	}
	out := new(HTTPStatusRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedResource) DeepCopyInto(out *ManagedResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedResource.
func (in *ManagedResource) DeepCopy() *ManagedResource {
	if in == nil {
		return nil
	}
	out := new(ManagedResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileConfig) DeepCopyInto(out *ProfileConfig) {
	*out = *in
	if in.AdmissionControl != nil {
		in, out := &in.AdmissionControl, &out.AdmissionControl
		*out = new(AdmissionControlOverride)
		**out = **in
	}
	if in.AdaptiveConcurrency != nil {
		in, out := &in.AdaptiveConcurrency, &out.AdaptiveConcurrency
		*out = new(AdaptiveConcurrencyOverride)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileConfig.
func (in *ProfileConfig) DeepCopy() *ProfileConfig {
	if in == nil {
		return nil
	}
	out := new(ProfileConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RateCondition) DeepCopyInto(out *RateCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RateCondition.
func (in *RateCondition) DeepCopy() *RateCondition {
	if in == nil {
		return nil
	}
	out := new(RateCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleConfig) DeepCopyInto(out *ScheduleConfig) {
	*out = *in
	if in.FromProfiles != nil {
		in, out := &in.FromProfiles, &out.FromProfiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleConfig.
func (in *ScheduleConfig) DeepCopy() *ScheduleConfig {
	if in == nil {
		return nil
	}
	out := new(ScheduleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SignalConfig) DeepCopyInto(out *SignalConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SignalConfig.
func (in *SignalConfig) DeepCopy() *SignalConfig {
	if in == nil {
		return nil
	}
	out := new(SignalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StreamingProtectionConfig) DeepCopyInto(out *StreamingProtectionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StreamingProtectionConfig.
func (in *StreamingProtectionConfig) DeepCopy() *StreamingProtectionConfig {
	if in == nil {
		return nil
	}
	out := new(StreamingProtectionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThresholdCondition) DeepCopyInto(out *ThresholdCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThresholdCondition.
func (in *ThresholdCondition) DeepCopy() *ThresholdCondition {
	if in == nil {
		return nil
	}
	out := new(ThresholdCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerCondition) DeepCopyInto(out *TriggerCondition) {
	*out = *in
	if in.SuccessRate != nil {
		in, out := &in.SuccessRate, &out.SuccessRate
		*out = new(RateCondition)
		**out = **in
	}
	if in.ServiceLatencyMs != nil {
		in, out := &in.ServiceLatencyMs, &out.ServiceLatencyMs
		*out = new(ThresholdCondition)
		**out = **in
	}
	if in.RPSAbove != nil {
		in, out := &in.RPSAbove, &out.RPSAbove
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerCondition.
func (in *TriggerCondition) DeepCopy() *TriggerCondition {
	if in == nil {
		return nil
	}
	out := new(TriggerCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerConfig) DeepCopyInto(out *TriggerConfig) {
	*out = *in
	in.When.DeepCopyInto(&out.When)
	if in.FromProfiles != nil {
		in, out := &in.FromProfiles, &out.FromProfiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerConfig.
func (in *TriggerConfig) DeepCopy() *TriggerConfig {
	if in == nil {
		return nil
	}
	out := new(TriggerConfig)
	in.DeepCopyInto(out)
	return out
}
